### ISSUE TITLE
POST application/x-www-form-urlencoded でリクエストするときのデータにハッシュ形式で指定できない

### ISSUE THREAD

**Issue by masakiq** [ryz310/my_api_client#122]
`my_api_client` gem を使って以下でリクエストしようとしたが、データにハッシュ形式で指定すると意図したリクエストにならない。

HTTP メソッド : POST
HTTP リクエストヘッダー : application/x-www-form-urlencoded

サンプルコード
```
body = {
  hoge: 'hoge',
  fuga: 'fuga'
}
headers = { 'Content-Type': 'application/x-www-form-urlencoded' }
post 'hoge/fuga', body: body, headers: headers
```

原因は `sawyer` gem の以下の箇所でデータをエンコードする際に、デフォルトの `sawyer` だと JSON 文字列形式に変換されてしまうため。

https://github.com/lostisland/sawyer/blob/a541a68be349a7982e24b80d94fe380a37b4805c/lib/sawyer/agent.rb#L96

---

とりあえずワークアラウンドとして以下のようにキーバリューのクエリ形式で渡すようにしたところ意図したとおりのリクエストができた。
```
body = {
  hoge: 'hoge',
  fuga: 'fuga'
}.to_a.map { |a| a.join('=') }.join('&')
```

**Comment by ryz310** [comment]
ご報告ありがとうございます 🙏 

ご指摘の通り、Sawyer から Faraday に `body` を渡す前に JSON へ変換する処理が入ってしまうので、`content-type` が `application/x-www-form-urlencoded` の場合は意図した結果にならないようです。
https://github.com/lostisland/sawyer/blob/a541a68be349a7982e24b80d94fe380a37b4805c/lib/sawyer/agent.rb#L96

将来的には対応したいのですが、まずは Sawyer の依存を解消してから対応したいと考えています。
`body` に渡すデータが String であれば Sawyer で変換されないので、ワークアラウンドの方法で対応をお願いします 🙏 

なお Rails だと `to_query` で変換して渡す、でも動くみたいですね 👀 

```rb
body = {
  hoge: 'hoge',
  fuga: 'fuga'
}.to_query
# => "fuga=fuga&hoge=hoge"
```
