### ISSUE TITLE
error_handling で status と json の組み合わせが意図したとおりに定義されていない

### ISSUE THREAD

**Issue by maeda1150** [ryz310/my_api_client#142]
MyApiClient クラスを継承した以下のような SampleApiClient クラスを作成し、RSpec を実行したところエラーに遭遇しテストが落ちました。

* sample_api_client.rb
```ruby
class SampleApiClient < MyApiClient
  retry_on MyApiClient::ServerError, wait: 0.1.seconds, attempts: 3
  error_handling status: 200, json: :forbid_nil, raise: SampleApiClientError
end
```

* sample_api_client_spec.rb
```ruby
RSpec.describe SampleApiClient, type: :api_client do
  it do
    expect { subject }
      .to be_handled_as_an_error(MyApiClient::ServerError)
      .after_retry(3).times
      .when_receive(status_code: 500)
  end
end
```

* error

```sh
expected to be handled as MyApiClient::ServerError, but it was handled as SampleApiClientError
```

---

ソースコードに以下の定義が `status code : 200` かつ `body : nil` という条件定義のように見えますが、実際は `status code : 500` かつ `body : nil` という条件にもひっかかってしまっているようです。
```ruby
  error_handling status: 200, json: :forbid_nil, raise: SampleApiClientError
```

`status code : 500` かつ `body : nil` の場合は上記エラーハンドルにひっかかからないように( 上記エラーハンドル定義の場合は `status code : 200` かつ `body :nil` の場合のみひっかかる )修正をお願いできますでしょうか。

**Comment by ryz310** [comment]
> ```ruby
> class SampleApiClient < MyApiClient
>   retry_on MyApiClient::ServerError, wait: 0.1.seconds, attempts: 3
>   error_handling status: 200, json: :forbid_nil, raise: SampleApiClientError
> end
> ```

手元で再現しようとしたんですが再現しなくて、調べてみてわかったんですが、 `status: 200` の部分が実は間違ってますね。。正しくは `status_code: 200` です。

`status` でも受け付けるようにするか、未定義の引数の場合はエラーにするかした方が良さそうですね。。

**Comment by ryz310** [comment]
#144 にて対応するのでこの Issue は close します。
