### ISSUE TITLE
`#stub_api_client_all` や `#stub_api_client` で例外のレスポンスをスタブ化する際に任意の HTTP ステータスコードを渡したい

### ISSUE THREAD

**Issue by daido1976** [ryz310/my_api_client#563]
## 概要

See. https://github.com/ryz310/my_api_client/blob/v0.20.0/README.jp.md#raise-option

README の上記箇所を参照したところ例外のレスポンスをスタブ化するには `#stub_api_client_all` や `#stub_api_client` の raise オプションとともに response オプションを利用すれば良さそうでした。

ただ、例外のレスポンスとして任意の HTTP ステータスコードを返そうと思ったのですが、以下の箇所で HTTP のステータスコードが `400` で決め打ちになっていたためできませんでした。

https://github.com/ryz310/my_api_client/blob/a587a9666abf5e621fecced441116277e38f1d76/lib/my_api_client/rspec/stub.rb#L140

## 期待する動作

以下のように、`#stub_api_client_all` や `#stub_api_client` で例外のテストをする際にレスポンスの HTTP ステータスコードも外部から注入できるようにしたいです。

```rb
stub_api_client_all(
  ExampleApiClient,
  request: {
    raise: MyApiClient::Error,
    response: { status: 404, message: 'error' }
  }
)
# or
stub_api_client_all(
  ExampleApiClient,
  request: {
    raise: MyApiClient::Error,
    status: 404,
    response: { message: 'error' },
  }
)
```

**Comment by ryz310** [comment]
@daido1976 貴重なご意見ありがとうございます！ `v0.21.0` で対応します 👍
